# Generated by Django 3.0.7 on 2020-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=20)),
                ('u_passwd', models.CharField(max_length=128)),
                ('u_avatar', models.ImageField(upload_to='images/User/%Y/%m/%d')),
                ('u_type', models.IntegerField()),
                ('u_tel', models.CharField(max_length=20)),
                ('u_email', models.CharField(blank=True, max_length=50)),
                ('u_intro', models.CharField(max_length=256, null=True)),
                ('u_sex', models.IntegerField()),
                ('u_age', models.IntegerField()),
                ('c_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
