# Generated by Django 3.0.6 on 2020-05-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=20)),
                ('u_passwd', models.CharField(max_length=20)),
                ('u_avatar', models.ImageField(upload_to='images/Users/%Y/%m/%d')),
                ('u_type', models.IntegerField()),
                ('u_tel', models.CharField(max_length=20)),
                ('u_email', models.CharField(blank=True, max_length=50)),
                ('u_intro', models.CharField(max_length=256, null=True)),
                ('u_sex', models.IntegerField()),
                ('u_age', models.IntegerField()),
            ],
        ),
    ]
