# Generated by Django 3.0.6 on 2020-05-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_picturegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=50)),
                ('h_status', models.IntegerField()),
                ('h_type', models.IntegerField()),
                ('h_intro', models.CharField(max_length=256)),
                ('h_price', models.IntegerField()),
                ('h_location', models.CharField(max_length=256)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.PictureGroup')),
            ],
        ),
    ]
