# Generated by Django 3.0.6 on 2020-05-23 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_status', models.IntegerField()),
                ('ro_type', models.IntegerField()),
                ('ro_amount', models.IntegerField()),
                ('ro_time', models.DateTimeField(auto_now_add=True)),
                ('ro_start', models.DateTimeField()),
                ('ro_end', models.DateTimeField()),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.House')),
                ('res_u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_u_id', to='common.Users')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_u_id', to='common.Users')),
            ],
        ),
    ]
