# Generated by Django 3.0.6 on 2020-05-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rentalorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='res_u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ro_res_u_id', to='common.Users'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_u_id', to='common.Users'),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_status', models.IntegerField()),
                ('sr_type', models.CharField(max_length=256)),
                ('sr_time', models.DateTimeField(auto_now_add=True)),
                ('fix_u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_fix_u_id', to='common.Users')),
                ('pg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.PictureGroup')),
                ('res_u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_res_u_id', to='common.Users')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_u_id', to='common.Users')),
            ],
        ),
    ]
