# Generated by Django 3.0.6 on 2020-05-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_supportrequestconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequestconversation',
            name='sr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SupportRequest'),
        ),
        migrations.AlterField(
            model_name='supportrequestconversation',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Users'),
        ),
    ]
