# Generated by Django 3.0.6 on 2020-05-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200523_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequestRating',
            fields=[
                ('srr_id', models.AutoField(primary_key=True, serialize=False)),
                ('srr_content', models.CharField(max_length=256)),
                ('srr_stars', models.IntegerField()),
                ('sr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SupportRequest')),
            ],
        ),
    ]
