# Generated by Django 3.0.7 on 2020-06-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('picgroup', '0001_initial'),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_status', models.IntegerField()),
                ('sr_type', models.IntegerField()),
                ('sr_content', models.TextField()),
                ('sr_time', models.DateTimeField(auto_now_add=True)),
                ('fix_u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_fix_u_id', to='account.User')),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_h_id', to='house.House')),
                ('pg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picgroup.PictureGroup')),
                ('res_u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_res_u_id', to='account.User')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_u_id', to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequestRating',
            fields=[
                ('srr_id', models.AutoField(primary_key=True, serialize=False)),
                ('srr_content', models.CharField(max_length=256)),
                ('srr_stars', models.IntegerField()),
                ('sr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.SupportRequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequestConversation',
            fields=[
                ('src_id', models.AutoField(primary_key=True, serialize=False)),
                ('src_content', models.CharField(max_length=256)),
                ('src_time', models.DateTimeField(auto_now_add=True)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picgroup.PictureGroup')),
                ('sr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.SupportRequest')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
