# Generated by Django 3.0.7 on 2020-06-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20200612_0242'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='h_id',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='ro_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sr_h_id', to='house.RentalOrder'),
            preserve_default=False,
        ),
    ]
