# Generated by Django 3.0.7 on 2020-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureGroup',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_1', models.ImageField(upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_2', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_3', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_4', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_5', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_6', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_7', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_8', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
                ('pg_9', models.ImageField(blank=True, null=True, upload_to='images/PictureGroup/%Y/%m/%d')),
            ],
        ),
    ]
