# Generated by Django 3.0.7 on 2020-06-10 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('picgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=50)),
                ('h_status', models.IntegerField()),
                ('h_term', models.IntegerField()),
                ('h_cap', models.IntegerField()),
                ('h_intro', models.TextField()),
                ('h_price', models.IntegerField()),
                ('h_location', models.CharField(max_length=256)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picgroup.PictureGroup')),
            ],
            managers=[
                ('randoms', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_status', models.IntegerField()),
                ('ro_type', models.IntegerField()),
                ('ro_amount', models.IntegerField()),
                ('ro_time', models.DateTimeField(auto_now_add=True)),
                ('ro_start', models.DateTimeField()),
                ('ro_end', models.DateTimeField()),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
                ('res_u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ro_res_u_id', to='account.User')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_u_id', to='account.User')),
            ],
        ),
    ]
