# Generated by Django 3.0.7 on 2020-06-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='house',
            managers=[
            ],
        ),
    ]
